#!/sbin/sh
#
rm -rf /system/app/AntHalService;
rm -rf /system/app/embms;
rm -rf /system/app/fastdormancy;
rm -rf /system/app/NfcNci;
rm -rf /system/app/Stk;
rm -rf /system/priv-app/CNEService;
rm -rf /system/priv-app/Tag;
sleep 1;
sed -i "s/ro.product.locale=.*./ro.product.locale=ru-RU/" /system/build.prop;
sed -i "s/persist.radio.ramdump_sdcard=.*./persist.radio.ramdump_sdcard=0/" /system/build.prop;
sed -i "s/persist.cne.feature=.*./persist.cne.feature=0/" /system/build.prop;
sed -i "s/persist.env.fastdorm.enabled=.*./persist.env.fastdorm.enabled=false/" /system/build.prop;
sed -i "s/persist.sys.mitalk.enable=.*./persist.sys.mitalk.enable=false/" /system/build.prop;
sed -i "s/ro.qualcomm.cabl=.*./ro.qualcomm.cabl=1/" /system/build.prop;
sed -i "s/qcom.hw.aac.encoder=.*./qcom.hw.aac.encoder=false/" /system/build.prop;
sed -i "s/persist.audio.fluence.voicecall=.*./persist.audio.fluence.voicecall=true/" /system/build.prop;
sed -i "s/persist.audio.fluence.speaker=.*./persist.audio.fluence.speaker=true/" /system/build.prop;
sleep 1;
echo "#" >> /system/build.prop;
echo "# user tweaks" >> /system/build.prop;
echo "#" >> /system/build.prop;
echo "# dalvik weaks" >> /system/build.prop;
echo "dalvik.vm.dex2oat-thread_count=4" >> /system/build.prop;
echo "dalvik.vm.dex2oat-filter=everything >> /system/build.prop;
echo "dalvik.vm.image-dex2oat-filter=everything" >> /system/build.prop;
echo "# adb tweaks" >> /system/build.prop;
echo "ro.adb.secure=0" >> /system/build.prop;
echo "persist.adb.notify=0" >> /system/build.prop;
echo "persist.service.adb.enable=1" >> /system/build.prop;
echo "persist.sys.usb.config=mtp,adb" >> /system/build.prop;
echo "# incoming call ring delay" >> /system/build.prop;
echo "ro.telephony.call_ring.delay=500 >> /system/build.prop;
echo "# picture quality" >> /system/build.prop;
echo "ro.media.enc.jpeg.quality=100" >> /system/build.prop;
echo "# system tuning" >> /system/build.prop;
echo "debug.performance.tuning=1" >> /system/build.prop;
echo "# qualcomm svi service activation" >> /system/build.prop;
echo "ro.qualcomm.svi=1" >> /system/build.prop;
echo "# qualcomm sensor tweaks" >> /system/build.prop;
echo "ro.qualcomm.sensors.qmd=true" >> /system/build.prop;
echo "ro.qualcomm.sensors.smd=true" >> /system/build.prop;
echo "ro.qualcomm.sensors.cmc=true" >> /system/build.prop;
echo "ro.qualcomm.sensors.vmd=true" >> /system/build.prop;
echo "ro.qualcomm.sensors.gtap=true" >> /system/build.prop;
echo "ro.qualcomm.sensors.pedometer=true" >> /system/build.prop;
echo "ro.qualcomm.sensors.pam=true" >> /system/build.prop;
echo "ro.qualcomm.sensors.scrn_ortn=true" >> /system/build.prop;
echo "ro.qualcomm.sensors.georv=true" >> /system/build.prop;
echo "ro.qualcomm.sensors.game_rv=true" >> /system/build.prop;
echo "ro.qti.sdk.sensors.gestures=true" >> /system/build.prop;
echo "ro.qc.sensors.step_detector=true" >> /system/build.prop;
echo "ro.qc.sensors.step_counter=true" >> /system/build.prop;
echo "ro.qc.sensors.max_geomag_rotvec=true" >> /system/build.prop;
echo "debug.qualcomm.sns.hal=w" >> /system/build.prop;
echo "debug.qualcomm.sns.daemon=w" >> /system/build.prop;
echo "debug.qualcomm.sns.libsensor1=w" >> /system/build.prop;
sleep 1;
echo "# init.d activation" >> /system/etc/init.qcom.post_boot.sh;
echo "busybox run-parts /system/etc/init.d/" >> /system/etc/init.qcom.post_boot.sh;
